# Generated by Django 2.1.3 on 2018-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.SlugField(blank=True, max_length=80, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
