# Generated by Django 2.1.3 on 2018-11-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181104_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_to_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
